In [1]:
# 시리즈

## 외부라이브러리 pandas 설치
## !pip install pandas 

## 리이브러리 불러오기
import pandas as pd

dict_data = {
    "a": 1, 
    "b": 2, 
    "c": 3
}

sr = pd.Series(dict_data)
print(type(sr))

<class 'pandas.Series'>

In [2]:
print(sr)

a    1
b    2
c    3
dtype: int64

In [3]:
## 인덱스 배열
## Series객체.index

print(sr.index)

Index(['a', 'b', 'c'], dtype='str')

In [4]:
## 데이터 값 배열
## Series객체.values

print(sr.values)

[1 2 3]

In [5]:
## 시리즈 인덱스 

import pandas as pd

list_data = ["2019-01-01", 3.14, "ABC", 100, True]
sr = pd.Series(list_data)
print(sr)

0    2019-01-01
1          3.14
2           ABC
3           100
4          True
dtype: object

In [6]:
## 인덱스 
print(sr.index)

RangeIndex(start=0, stop=5, step=1)

In [7]:
## values
print(sr.values)

['2019-01-01' 3.14 'ABC' 100 True]

In [8]:
## 시리즈 객체의 데이터 타입 확인
print(sr.dtype)

object

In [9]:
## 원소의 개수 확인하기 
print(len(sr))

5

In [ ]:
## 배열의 형태
## shape 속성
sr.shape

(5,)

In [11]:
## 데이터의 구조의 차원수
## ndim속성
print(sr.ndim)

1

In [16]:
# 원소선택

import pandas as pd

tup_data = ("영인", "2010-05-01", "여", True)
sr = pd.Series(tup_data, index=["이름", "생년월일", "성별", "학생여부"])
print(sr)

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [18]:
## 원소선택

# print(sr[0])
print(sr["이름"])

영인

In [21]:
sr[0]

KeyError: 0

In [22]:
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [26]:
# print(sr["생년월일", "성별"])
print(sr[["생년월일", "성별"]])

생년월일    2010-05-01
성별               여
dtype: object

In [28]:
print(sr)
print(sr[1:2])
print(sr["생년월일":"성별"])

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object
생년월일    2010-05-01
dtype: object
생년월일    2010-05-01
성별               여
dtype: object

In [30]:
# 시리즈 객체를 만드는 특수한 방법

import pandas as pd

a = pd.Series()
print(a)

Series([], dtype: object)

In [31]:
b = pd.Series(5)
print(b)

0    5
dtype: int64

In [33]:
c = pd.Series("a", index=["a", "b", "c"])
print(c)

a    a
b    a
c    a
dtype: str

In [35]:
# 데이터프레임
## 딕셔너리 -> 데이터프레임으로 변환
## pandas.DataFrame(딕셔너리)

import pandas as pd

dict_data = {
    "c0": [1, 2, 3], 
    "c1": [4, 5, 6], 
    "c2": [7, 8, 9], 
    "c3": [10, 11, 12], 
    "c4": [13, 14, 15]
}

## 시리즈로 변환한 값
sr = pd.Series(dict_data)
print(sr)

## 데이터프레임으로 변환한 값
df = pd.DataFrame(dict_data)
print(df)

c0       [1, 2, 3]
c1       [4, 5, 6]
c2       [7, 8, 9]
c3    [10, 11, 12]
c4    [13, 14, 15]
dtype: object
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [36]:
print(type(df))

<class 'pandas.DataFrame'>

In [39]:
# 행 인덱스 / 열 이름 설정

import pandas as pd 

list_data = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"], 
]

df = pd.DataFrame(list_data, index=["준서", "예은"], columns=["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [41]:
## 인덱스 명 가져오기
print(df.index)

## 열 이름 가져오기
print(df.columns)

Index(['준서', '예은'], dtype='str')
Index(['나이', '성별', '학교'], dtype='str')

In [44]:
print(df)

df.index = ["학생1", "학생2"]
df.columns = ["연령", "남녀", "소속"]

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중
     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [45]:
print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [46]:
import pandas as pd 

list_data = [
    [15, "남", "덕영중"], 
    [17, "여", "수리중"], 
]

df = pd.DataFrame(list_data, index=["준서", "예은"], columns=["나이", "성별", "학교"])

print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [48]:
df = df.rename(columns={
    "나이" : "연령", 
    "성별" : "남녀", 
    "학교" : "소속"
})

print(df)

    연령 남녀   소속
준서  15  남  덕영중
예은  17  여  수리중

In [49]:
df = df.rename(index={
    "준서": "학생1", 
    "예은": "학생2"
})

print(df)

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [50]:
# 행/열 삭제 
## 행삭제 -> DataFrame객체.drop(행인덱스 또는 배열, axis=0 또는 axis="index" )
## 열삭제 -> DataFrame객체.drop(열이름 또는 배열, axis=1 또는 axis="columns" )

In [53]:
import pandas as pd

exam_data = {
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data, index=["서준", "우현", "인아"])
print(df)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [52]:
df

   수학  영어   음악   체육
0  90  98   95  100
1  80  89   95   90
2  70  95  100   90

In [58]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   95  100
인아  70  95  100   90

In [59]:
df3 = df.copy()
df3

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [62]:
df3 = df3.drop("영어", axis=1)

In [63]:
df3

    수학   음악   체육
서준  90   95  100
우현  80   95   90
인아  70  100   90

In [64]:
df3 = df.copy()
df3

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [66]:
df3 = df3.drop(["영어", "음악"],  axis=1)
df3

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [67]:
df4 = df.copy()
df4

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [68]:
df4 = df4.drop(["수학", "체육"], axis="columns")
df4

    영어   음악
서준  98   95
우현  89   95
인아  95  100

In [71]:
df5 = df.copy()
df5 = df5.drop(columns=["수학"])
df5

    영어   음악   체육
서준  98   95  100
우현  89   95   90
인아  95  100   90

In [81]:
# 행선택
##  loc 인덱서

print(df)
print()
label1 = df.loc["서준"]
position1 = df.iloc[0]

print(label1)
print()
print(position1)

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     95
체육    100
Name: 서준, dtype: int64

In [82]:
df

    수학  영어   음악   체육
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [87]:
label2 = df.loc[["서준", "우현"]]
position2 = df.iloc[[0, 1]]
position2

    수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90

In [89]:
# 열선택

import pandas as pd 

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
print(type(df))
df

<class 'pandas.DataFrame'>

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [ ]:
# type(df["수학"]) -> Series 타입
math1 = df["수학"]

pandas.Series

In [93]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [95]:
print(df.영어)
print(type(df.영어))

0    98
1    89
2    95
Name: 영어, dtype: int64
<class 'pandas.Series'>

In [97]:
music_gym = df[["음악", "체육"]]
music_gym
type(music_gym)

pandas.DataFrame

In [98]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [99]:
math1 = df["수학"]
math2 = df[["수학"]]

print(math1)
print(math2)
print()
print(type(math1))
print(type(math2))

0    90
1    80
2    70
Name: 수학, dtype: int64
   수학
0  90
1  80
2  70

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [100]:
## 범위 슬라이싱 
## 데이터프레임객체.iloc[ 시작인덱스 : 끝인덱스 : 간격 ]

df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [101]:
df.iloc[0]

이름     서준
수학     90
영어     98
음악     95
체육    100
Name: 0, dtype: object

In [103]:
df.iloc[ : :2]

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
2  인아  70  95  100   90

In [106]:
df.iloc[0:2]

   이름  수학  영어  음악   체육
0  서준  90  98  95  100
1  우현  80  89  95   90

In [107]:
df.iloc[ :3:2]

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
2  인아  70  95  100   90

In [108]:
df.iloc[::-1]

   이름  수학  영어   음악   체육
2  인아  70  95  100   90
1  우현  80  89   95   90
0  서준  90  98   95  100

In [109]:
## 원소선택 
matrix = [
    [1, 2, 3],
    [4, 5, 6], 
    [7, 8, 9]
]
matrix[1][1]

5

In [110]:
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [112]:
import pandas as pd 

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [115]:
## 인덱스이름: DF객체.loc[행인덱스, 열이름]
## 정수위치인덱스: DF객체.iloc[행번호, 열번호]

print(df.loc["서준", "음악"])
print(df.iloc[0, 2])

95
95

In [116]:
# 열추가
## DF객체["추가하려는 열이름"] = 데이터값

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [118]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   95  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [120]:
df["미술"] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   95  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [122]:
# 행추가
## DF객체.loc["새로운행이름"] = 데이터 값 또는 배열

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)

df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [125]:
df.loc[2]
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [127]:
df.loc[4] = ["동규", 90, 80, 70, 60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [128]:
df.loc["행5"] = df.loc[0]
df

    이름  수학  영어   음악   체육
0   서준  90  98   95  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5  서준  90  98   95  100

In [129]:
df.loc["행6"] = df.loc[3]
df

    이름  수학  영어   음악   체육
0   서준  90  98   95  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5  서준  90  98   95  100
행6   0   0   0    0    0

In [130]:
## 원소 값 변경
exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}
df = pd.DataFrame(exam_data)

df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [132]:
df.iloc[0,0]
df.loc["서준", "수학"]

np.int64(90)

In [134]:
df

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [141]:
# df.iloc[0].iloc[3]
df.iloc[0, 3]

np.int64(100)

In [146]:
df.loc["서준"]["체육"] = 90
df

C:\Users\PC\AppData\Local\Temp\ipykernel_10860\52186648.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df.loc["서준"]["체육"] = 90

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [147]:
df.loc["서준", "체육"] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   95  50
우현  80  89   95  90
인아  70  95  100  90

In [148]:
## 행, 열의 위치 바꾸기
## DF객체.transpose()
## DT객체.T

exam_data = {
    "이름": ["서준", "우현", "인아"],
    "수학": [90, 80, 70], 
    "영어": [98, 89, 95], 
    "음악": [95, 95, 100], 
    "체육": [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [151]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   95  95  100
체육  100  90   90

In [152]:
df.T

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90