In [1]:
import pandas as pd
import seaborn as sns 

titanic = sns.load_dataset("titanic")
df = titanic.loc[ : , ["age", "fare"]]
df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [2]:
## 불린 인덱싱

df["age"] < 20

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [3]:
cond = df["age"] < 20
df[cond]

      age     fare
7     2.0  21.0750
9    14.0  30.0708
10    4.0  16.7000
14   14.0   7.8542
16    2.0  29.1250
..    ...      ...
855  18.0   9.3500
869   4.0  11.1333
875  15.0   7.2250
877  19.0   7.8958
887  19.0  30.0000

[164 rows x 2 columns]

In [4]:
df.loc[df["age"] < 20]

      age     fare
7     2.0  21.0750
9    14.0  30.0708
10    4.0  16.7000
14   14.0   7.8542
16    2.0  29.1250
..    ...      ...
855  18.0   9.3500
869   4.0  11.1333
875  15.0   7.2250
877  19.0   7.8958
887  19.0  30.0000

[164 rows x 2 columns]

In [10]:
mask1 = (titanic.age >= 10) & (titanic.age < 20 )
df_teenage = titanic[mask1]
df_teenage.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
38,0,3,female,18.0,2,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False

In [13]:
mask2 = (titanic.age < 10) & (titanic.sex == "female")
df_female_under10 = titanic.loc[mask2]
df_female_under10.shape

(30, 15)

In [14]:
mask3 = (titanic.age < 10) | (titanic.age >= 60) 
mask3

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: age, Length: 891, dtype: bool

In [17]:
df_under10_morethan60 = titanic.loc[mask3, ["age", "sex", "alone"]]
df_under10_morethan60

       age     sex  alone
7     2.00    male  False
10    4.00  female  False
16    2.00    male  False
24    8.00  female  False
33   66.00    male   True
..     ...     ...    ...
831   0.83    male  False
850   4.00    male  False
851  74.00    male   True
852   9.00  female  False
869   4.00    male  False

[88 rows x 3 columns]

In [18]:
## query() 매서드 활용

import pandas as pd
import seaborn as sns 

titanic = sns.load_dataset("titanic")
df = titanic.loc[ : , ["age", "fare"]]
df

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [19]:
## 20세 미만의 조건을 만족하는 행을 필터링
df.query("age < 20")

      age     fare
7     2.0  21.0750
9    14.0  30.0708
10    4.0  16.7000
14   14.0   7.8542
16    2.0  29.1250
..    ...      ...
855  18.0   9.3500
869   4.0  11.1333
875  15.0   7.2250
877  19.0   7.8958
887  19.0  30.0000

[164 rows x 2 columns]

In [20]:
df.query("age >= 20 or fare < 15")

      age     fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
889  26.0  30.0000
890  32.0   7.7500

[728 rows x 2 columns]

In [22]:
## isin() 매서드 활용

## DF객체.isin(추출 값의 리스트)

import pandas as pd
import seaborn as sns 

titanic = sns.load_dataset("titanic")

pd.set_option("display.max_columns", 10)

titanic.head()

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,...,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,...,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,...,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,...,False,C,Southampton,yes,False
4,0,3,male,35.0,0,...,True,NaN,Southampton,no,True

In [24]:
mask1 = titanic["embark_town"] == "Southhampton"
mask2 = titanic["embark_town"] == "Queenstown"

df_boolean = titanic[mask1 | mask2]

df_boolean

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,...,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,...,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...
790,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
825,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
828,1,3,male,NaN,0,...,True,NaN,Queenstown,yes,True
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True

In [25]:
isin_filter = titanic["embark_town"].isin(["Southhampton", "Queenstown"])
df_isin = titanic[isin_filter]
df_isin

,survived,pclass,sex,age,sibsp,...,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
16,0,3,male,2.0,4,...,False,NaN,Queenstown,no,False
22,1,3,female,15.0,0,...,False,NaN,Queenstown,yes,True
28,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
32,1,3,female,NaN,0,...,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...
790,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
825,0,3,male,NaN,0,...,True,NaN,Queenstown,no,True
828,1,3,male,NaN,0,...,True,NaN,Queenstown,yes,True
885,0,3,female,39.0,0,...,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,...,True,NaN,Queenstown,no,True